### ISSUE TITLE
Proposal markdown wrapper missing ordered-list styles

### ISSUE THREAD

**Issue by neatonk** [ensdao/ens-small-grants#12]
Hi @gskril. I just submitted a proposal and noticed that ordered lists are not being rendered correctly. The markup is fine, but the css is lacking the styles needed for proper numbers and line spacing.

I believe this can be fixed [here](https://github.com/ensdao/ens-small-grants/blob/176a8053797c9e70114328f35c35590f57b111dd/src/screens/Proposal.tsx#L118-L126) using something like what you've got for unordered lists.

For reference, here is my [proposal](https://ensgrants.xyz/rounds/21/proposals/505).

You can see under the "Here’s how it works:" heading there is an order list. That section currently renders like this:

<img width="938" alt="Screen Shot 2023-03-17 at 11 33 57 PM" src="https://user-images.githubusercontent.com/21178/226082671-83798510-9bd3-45d7-8269-48233fa423a3.png">

It should probably render like this instead:

<img width="947" alt="Screen Shot 2023-03-17 at 11 36 56 PM" src="https://user-images.githubusercontent.com/21178/226082672-fa79a19e-0664-4486-a431-86934a99b0c1.png">

Here is the additional css added in the second screenshot:

```css
ol {
  margin-inline-start: 1.5rem;
  list-style-type: decimal;
  line-height: 1.625;
}
```

I'd be happy to throw a PR together for this if needed. 
Let me know. 

Also, the site was a joy to use. 
Thanks!

**Comment by gskril** [comment]
Hey @neatonk, thanks for flagging this! I'm pushing a fix now
