### ISSUE TITLE
Can't Vote

### ISSUE THREAD

**Issue by GriffGreen** [ensdao/ens-small-grants#19]
Not sure what the issue is... It says snapshot... but I don't think so.

<img width="510" alt="Screenshot 2024-04-08 at 12 29 20 PM" src="https://github.com/ensdao/ens-small-grants/assets/14945613/5b5475dd-fcd6-458f-8441-969d25df1cf5">

**Comment by coltron-code** [comment]
Resolved. Reverted to token voting. See: https://github.com/ensdao/ens-small-grants/commit/2fe7f6951f0a9a4739682b0ba428dbe182fce52b
